tax_categories = ['Advertising and marketing',
                    'Contract Labor',
                    'Cost of Goods/Purchases',
                    'Equipment or Furniture',
                    'Fees (ie bank)',
                    'Income',
                    'Insurance',
                    'Local Meals',
                    'Office Expenses',
                    'Other or Not sure?',
                    'Owner Draw or Investment',
                    'Rent Expense',
                    'Repairs and Maintenance',
                    'Research and Education',
                    'Subscriptions',
                    'Supplies',
                    'Taxes and Licenses',
                    'Travel (airfare, lyft, parking)',
                    'Travel Meals',
                    'Utilities', ]